name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR
        run: |
          ./mvnw package

      - name: Transfer JAR to EC2 instance
        run: |
          cd target
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -P ${{ secrets.EC2_PORT }} BlogBackned-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/blog/

      - name: SSH into EC2 instance and stop service
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "sudo systemctl stop blogBackend.service"

      - name: SSH into EC2 instance and update service
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "sudo systemctl daemon-reload"

      - name: SSH into EC2 instance and start service
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "sudo systemctl start blogBackend.service"
